/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinema_proyect;

import Conex.Conexion;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author monit
 */
public class contratar extends javax.swing.JFrame {
    public static int usuario;
    Conexion cc = new Conexion();
    Connection con = cc.Conexion();
    String seccion[][] = new String[20][2];
    String puesto[][] = new String[20][2];
    String privilegios[][] = new String[20][2];
    String sexo[][] = new String[20][2];
    
    /**
     * Creates new form contratar
     */
    public contratar(int id_usuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        usuario = id_usuario;
        text_usuario.setText("UsuarioID: "+usuario);
        
        String stmt = "select * from seccion";
        String stmt1 = "select * from puesto";
        String stmt2 = "select * from privilegios";
        String stmt3 = "select * from sexo";
        try{
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(stmt);
            int s=0;
            int p=0;
            int pr=0;
            int sx = 0;
            while(rs.next()){
                seccion[s][0] = String.valueOf(rs.getInt("id_seccion"));
                seccion[s][1] = rs.getString("seccion");
                s++;
            }
            Statement st1 = con.createStatement();
            ResultSet rs1 = st1.executeQuery(stmt1);
            while(rs1.next()){
                puesto[p][0] = String.valueOf(rs1.getInt("id_puesto"));
                puesto[p][1] = rs1.getString("puesto");
                p++;
            }
            Statement st2 = con.createStatement();
            ResultSet rs2 = st2.executeQuery(stmt2);
            while(rs2.next()){
                privilegios[pr][0] = String.valueOf(rs2.getInt("id_privilegios"));
                privilegios[pr][1] = rs2.getString("privilegios");
                pr++;
            }
            Statement st3 = con.createStatement();
            ResultSet rs3 = st3.executeQuery(stmt3);
            while(rs3.next()){
                sexo[sx][0] = String.valueOf(rs3.getInt("id_sexo"));
                sexo[sx][1] = rs3.getString("sexo");
                sx++;
            }
            for(int i = 0; i < seccion.length; i++){
                if(seccion[i][1] != null){
                    text_seccion.addItem(seccion[i][1]);
                }
            }
            for(int i = 0; i < puesto.length; i++){
                if(puesto[i][1] != null){
                    text_puesto.addItem(puesto[i][1]);
                }
            }
            for(int i = 0; i < privilegios.length; i++){
                if(privilegios[i][1] != null){
                    text_privilegios.addItem(privilegios[i][1]);
                }
            }
            for(int i = 0; i < sexo.length; i++){
                if(sexo[i][1] != null){
                    text_sexo.addItem(sexo[i][1]);
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error: "+e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        text_usuario = new javax.swing.JLabel();
        text_sa = new javax.swing.JTextField();
        text_nit = new javax.swing.JTextField();
        text_pn = new javax.swing.JTextField();
        text_sn = new javax.swing.JTextField();
        text_pa = new javax.swing.JTextField();
        text_user = new javax.swing.JTextField();
        text_celular = new javax.swing.JTextField();
        text_fecha = new javax.swing.JTextField();
        text_profesion = new javax.swing.JTextField();
        text_correo = new javax.swing.JTextField();
        text_dire = new javax.swing.JTextField();
        text_password = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        text_privilegios = new javax.swing.JComboBox<>();
        text_puesto = new javax.swing.JComboBox<>();
        text_seccion = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        text_cui = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        text_sexo = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("USUARIO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 193, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CONTRASEÑA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 193, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PRIVILEGIOS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 193, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PUESTO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 168, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SECCION");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 168, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("PRIMER NOMBRE");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 168, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("SEGUNDO NOMBRE");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 168, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("SEGUNDO APELLIDO");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("PRIMER APELLIDO");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 168, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("CELULAR");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 193, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("FECHA NACIMIENTO   (Y-m-d)");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 270, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("PROFESION");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 193, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("CORREO ELECTRONICO");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("DIRECCION");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 190, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("NIT");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 168, 30));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel19.setText("CONTRATAR");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        text_usuario.setText("Usuario: ");
        jPanel1.add(text_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 150, -1));
        jPanel1.add(text_sa, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 230, 30));
        jPanel1.add(text_nit, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 230, 30));
        jPanel1.add(text_pn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 230, 30));

        text_sn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_snActionPerformed(evt);
            }
        });
        jPanel1.add(text_sn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 230, 30));
        jPanel1.add(text_pa, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 230, 30));
        jPanel1.add(text_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, 230, 30));
        jPanel1.add(text_celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, 230, 30));
        jPanel1.add(text_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, 150, 30));
        jPanel1.add(text_profesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 230, 30));
        jPanel1.add(text_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 230, 30));
        jPanel1.add(text_dire, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 230, 30));
        jPanel1.add(text_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, 230, 30));

        jButton1.setText("CONTRATAR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, 230, 40));

        jPanel1.add(text_privilegios, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 230, 30));

        jPanel1.add(text_puesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 230, 30));

        jPanel1.add(text_seccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 230, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("CUI");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 168, 30));
        jPanel1.add(text_cui, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 230, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("SEXO");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 168, 30));

        jPanel1.add(text_sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 230, 30));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/return.png"))); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(833, 10, 50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_snActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_snActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_snActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        contratar();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        regresar();
    }//GEN-LAST:event_jButton3MouseClicked
    public void regresar(){
        String us = "select id_privilegios from usuario where id_usuario = '"+usuario+"'";
        int result = 0;
        try{
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(us);
            
            if(rs.next()){
                result = 1;
                if(result == 1){
                    int privilegios = rs.getInt("id_privilegios");
                    if(privilegios == 1){
                        admin form = new admin(usuario);
                        form.setVisible(true);
                        this.dispose();
                    }else if(privilegios == 2){
                        Ventas form = new Ventas(usuario);
                        form.setVisible(true);
                        this.dispose();
                    }else if(privilegios == 3){
                        bodega form = new bodega(usuario);
                        form.setVisible(true);
                        this.dispose();
                    }else if(privilegios == 4){
                        rrhh form = new rrhh(usuario);
                        form.setVisible(true);
                        this.dispose();
                    }
                }
            }else{
                System.out.println("Error: ");
            }
        }catch(Exception e){
            System.out.println("Error: " + e);
        }
    }
    
    public void contratar(){
        boolean exito = false;
        String cui = text_cui.getText();
        String nit = text_nit.getText();
        String pn = text_pn.getText();
        String sn = text_sn.getText();
        String pa = text_pa.getText();
        String sa = text_sa.getText();
        String direccion = text_dire.getText();
        String correo = text_correo.getText();
        String profesion = text_profesion.getText();
        String dob = text_fecha.getText();
        String celular = text_celular.getText();
        String user = text_user.getText();
        String pass = text_password.getText();
        int id_puesto = Integer.parseInt(puesto[text_puesto.getSelectedIndex()][0]);
        int id_seccion = Integer.parseInt(seccion[text_seccion.getSelectedIndex()][0]);
        int id_privilegios = Integer.parseInt(privilegios[text_privilegios.getSelectedIndex()][0]);
        int id_sexo = Integer.parseInt(sexo[text_sexo.getSelectedIndex()][0]);
        int id_usuario = 0;
        String stmt = "select * from usuario where usuario = '"+user+"'";
        String stmt1 = "insert into usuario (id_privilegios,usuario,contrasena) values ('"+id_privilegios+"','"+user+"','"+pass+"')";
        try{
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(stmt);
            if(!rs.next()){
                st.executeUpdate(stmt1);
                stmt = "select id_usuario from usuario where usuario = '"+user+"'";
                rs = st.executeQuery(stmt);
                if(rs.next()){
                    id_usuario = rs.getInt("id_usuario");
                }
                String insert = "insert into empleado values('"+cui+"','"+id_sexo+"','"+id_usuario+"','"+id_puesto+"','"+id_seccion+"','1','"+pn+"','"+sn+"','"+pa+"','"+sa+"','"+nit+"',CURDATE(),'"+direccion+"','"+correo+"','"+profesion+"','"+dob+"','"+celular+"')";
                st.executeUpdate(insert);
                JOptionPane.showMessageDialog(null,"Empleado contratado con exito");
            }else{
                JOptionPane.showMessageDialog(null,"Error: Nombre de Usuario ya en uso");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error: "+e);
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(contratar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(contratar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(contratar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(contratar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new contratar(usuario).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField text_celular;
    private javax.swing.JTextField text_correo;
    private javax.swing.JTextField text_cui;
    private javax.swing.JTextField text_dire;
    private javax.swing.JTextField text_fecha;
    private javax.swing.JTextField text_nit;
    private javax.swing.JTextField text_pa;
    private javax.swing.JTextField text_password;
    private javax.swing.JTextField text_pn;
    private javax.swing.JComboBox<String> text_privilegios;
    private javax.swing.JTextField text_profesion;
    private javax.swing.JComboBox<String> text_puesto;
    private javax.swing.JTextField text_sa;
    private javax.swing.JComboBox<String> text_seccion;
    private javax.swing.JComboBox<String> text_sexo;
    private javax.swing.JTextField text_sn;
    private javax.swing.JTextField text_user;
    private javax.swing.JLabel text_usuario;
    // End of variables declaration//GEN-END:variables
}
