/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinema_proyect;

import Conex.Conexion;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author monit
 */
public class EDasiento extends javax.swing.JFrame {
    public static int usuario;
    Conexion cc = new Conexion();
    Connection con = cc.Conexion();
    String[] id_sala = new String[100];
    String[][] asientos = new String[1000][3];
    public EDasiento(int id_usuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        usuario = id_usuario;
        text_usuario.setText("UsuarioID: "+usuario);
        String stmt = "select * from sala";
        try{
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(stmt);
            int i=0;
            while(rs.next()){
                id_sala[i] = rs.getString("id_sala");
                if(id_sala[i] != null){
                    text_sala.addItem(id_sala[i]);
                }
                i++;
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error: "+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        text_asiento = new javax.swing.JComboBox<>();
        text_sala = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        text_uso = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        text_usuario = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setText("ASIENTOS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel3.setText("HABILITAR/DESHABILITAR");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        text_asiento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                text_asientoItemStateChanged(evt);
            }
        });
        jPanel1.add(text_asiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 160, 40));

        text_sala.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                text_salaItemStateChanged(evt);
            }
        });
        jPanel1.add(text_sala, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 160, 40));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("HABILITAR / DESHABILITAR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 470, 60));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ASIENTO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 100, 40));

        text_uso.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        text_uso.setText("DISPONIBLE PARA USO: ");
        jPanel1.add(text_uso, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 470, 40));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SALA");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 100, 40));

        text_usuario.setText("Usuario: ");
        jPanel1.add(text_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 150, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/return.png"))); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(833, 10, 50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_salaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_text_salaItemStateChanged
        
        llenar_asientos();
    }//GEN-LAST:event_text_salaItemStateChanged

    private void text_asientoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_text_asientoItemStateChanged
        llenar_estado();
    }//GEN-LAST:event_text_asientoItemStateChanged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        en_able();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        regresar();
    }//GEN-LAST:event_jButton3MouseClicked
    public void regresar(){
        String us = "select id_privilegios from usuario where id_usuario = '"+usuario+"'";
        int result = 0;
        try{
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(us);
            
            if(rs.next()){
                result = 1;
                if(result == 1){
                    int privilegios = rs.getInt("id_privilegios");
                    if(privilegios == 1){
                        admin form = new admin(usuario);
                        form.setVisible(true);
                        this.dispose();
                    }else if(privilegios == 2){
                        Ventas form = new Ventas(usuario);
                        form.setVisible(true);
                        this.dispose();
                    }else if(privilegios == 3){
                        bodega form = new bodega(usuario);
                        form.setVisible(true);
                        this.dispose();
                    }else if(privilegios == 4){
                        rrhh form = new rrhh(usuario);
                        form.setVisible(true);
                        this.dispose();
                    }
                }
            }else{
                System.out.println("Error: ");
            }
        }catch(Exception e){
            System.out.println("Error: " + e);
        }
    }
    
    public void en_able(){
        String id_asiento = asientos[text_asiento.getSelectedIndex()][0];
        int numero = Integer.parseInt(asientos[text_asiento.getSelectedIndex()][2]);
        String text = "";
        if(numero == 1){
            numero = 0;
            text = "Deshabilitado con exito";
        }else{
            numero = 1;
            text = "Habilitado con exito";
        }
        String stmt = "update asientos set disponibilidad_uso = '"+numero+"' where id_asientos = '"+id_asiento+"'";
        try{
            Statement st = con.createStatement();
            st.executeUpdate(stmt);
            llenar_asientos();
            llenar_estado();
            JOptionPane.showMessageDialog(null,text);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error: "+e);
        }
    }
    public void llenar_estado(){
        int id = text_asiento.getSelectedIndex();
        String disponible = "";
        if(id>=0){
            int numero = Integer.parseInt(asientos[id][2]);
            if(numero == 1){
                disponible = "HABILITADO";
            }else if(numero == 0){
                disponible = "DESHABILITADO";
            }else{
                disponible = "N / A";
            }
        }
        text_uso.setText("DISPONIBLE PARA USO: "+disponible);
    }
    
    public void llenar_asientos(){
        String id = id_sala[text_sala.getSelectedIndex()];
        text_asiento.removeAllItems();
        asientos = new String[1000][3];
        int i=0;
        String stmt = "select * from asientos where id_sala = '"+id+"'";
        try{
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(stmt);
            while(rs.next()){
                asientos[i][0] = rs.getString("id_asientos");
                asientos[i][1] = rs.getString("no_asiento");
                asientos[i][2] = rs.getString("disponibilidad_uso");
                if(asientos[i][1] != null){
                    text_asiento.addItem(asientos[i][1]);
                }
                i++;
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error: "+e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EDasiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EDasiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EDasiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EDasiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EDasiento(usuario).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> text_asiento;
    private javax.swing.JComboBox<String> text_sala;
    private javax.swing.JLabel text_uso;
    private javax.swing.JLabel text_usuario;
    // End of variables declaration//GEN-END:variables
}
