/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinema_proyect;
import Conex.Conexion;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author monit
 */
public class funcion extends javax.swing.JFrame {
    public static int usuario;
    Conexion cc = new Conexion();
    Connection con = cc.Conexion();
    String movies[][] = new String[20][5];
    String salas[][] =  new String[100][2];
    /**
     * Creates new form funcion
     */
    public funcion(int id_usuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        usuario = id_usuario;
        text_usuario.setText("UsuarioID: "+usuario);
        int result = 0;
        String stmt = "select p.id_pelicula, p.duracion, f.formato, p.nombre from pelicula p inner join formato f on p.id_formato = f.id_formato where id_estado = 1";
        try{
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(stmt);
            while(rs.next()){
                movies[result][0] = String.valueOf(rs.getInt("id_pelicula"));
                movies[result][1] = rs.getString("nombre");
                movies[result][2] = rs.getString("formato");
                movies[result][3] = String.valueOf(rs.getInt("duracion"));
                movies[result][4] = movies[result][1]+" ---"+movies[result][2]+"---";
                text_pelicula.addItem(movies[result][4]);
                result ++;
            }
        }catch(Exception e){
            System.out.println("Error: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        text_usuario = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        text_pelicula = new javax.swing.JComboBox<>();
        text_sala = new javax.swing.JComboBox<>();
        text_minutos = new javax.swing.JComboBox<>();
        text_anio = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        text_hora_fin = new javax.swing.JLabel();
        text_hora = new javax.swing.JComboBox<>();
        text_mes = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        text_dia = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel3.setText("AGREGAR FUNCION");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        text_usuario.setText("Usuario: ");
        jPanel1.add(text_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 150, -1));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("SALA");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 168, 30));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("PELICULA");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 168, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText(":");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 50, 30));

        text_pelicula.setBackground(new java.awt.Color(51, 255, 204));
        text_pelicula.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                text_peliculaItemStateChanged(evt);
            }
        });
        jPanel1.add(text_pelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 300, 30));

        text_sala.setBackground(new java.awt.Color(51, 255, 204));
        text_sala.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                text_salaItemStateChanged(evt);
            }
        });
        jPanel1.add(text_sala, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 300, 30));

        text_minutos.setBackground(new java.awt.Color(51, 255, 204));
        text_minutos.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        text_minutos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        text_minutos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                text_minutosItemStateChanged(evt);
            }
        });
        text_minutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_minutosActionPerformed(evt);
            }
        });
        jPanel1.add(text_minutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 70, 30));

        text_anio.setBackground(new java.awt.Color(51, 255, 204));
        text_anio.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        text_anio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2021", "2022" }));
        jPanel1.add(text_anio, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, -1, 30));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("HORA FIN");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 168, 30));

        text_hora_fin.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        text_hora_fin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(text_hora_fin, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 150, 30));

        text_hora.setBackground(new java.awt.Color(51, 255, 204));
        text_hora.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        text_hora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        text_hora.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                text_horaItemStateChanged(evt);
            }
        });
        jPanel1.add(text_hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 70, 30));

        text_mes.setBackground(new java.awt.Color(51, 255, 204));
        text_mes.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        text_mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jPanel1.add(text_mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 70, 30));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("FECHA:");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 160, 30));

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel27.setText("DIA        MES      AÑO");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 210, 30));

        text_dia.setBackground(new java.awt.Color(51, 255, 204));
        text_dia.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        text_dia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        text_dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_diaActionPerformed(evt);
            }
        });
        jPanel1.add(text_dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 70, 30));

        jButton1.setBackground(new java.awt.Color(51, 255, 204));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("CREAR NUEVA FUNCION");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 470, 50));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("HORA INICIO");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 168, 30));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/return.png"))); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(833, 10, 50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_minutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_minutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_minutosActionPerformed

    private void text_diaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_diaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_diaActionPerformed

    private void text_salaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_text_salaItemStateChanged
        
    }//GEN-LAST:event_text_salaItemStateChanged

    private void text_peliculaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_text_peliculaItemStateChanged
        llenar_sala();
        hora_fin();
    }//GEN-LAST:event_text_peliculaItemStateChanged

    private void text_horaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_text_horaItemStateChanged
        hora_fin();
    }//GEN-LAST:event_text_horaItemStateChanged

    private void text_minutosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_text_minutosItemStateChanged
        hora_fin();
    }//GEN-LAST:event_text_minutosItemStateChanged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        crear_funcion();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        regresar();
    }//GEN-LAST:event_jButton3MouseClicked
    public void regresar(){
        String us = "select id_privilegios from usuario where id_usuario = '"+usuario+"'";
        int result = 0;
        try{
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(us);
            
            if(rs.next()){
                result = 1;
                if(result == 1){
                    int privilegios = rs.getInt("id_privilegios");
                    if(privilegios == 1){
                        admin form = new admin(usuario);
                        form.setVisible(true);
                        this.dispose();
                    }else if(privilegios == 2){
                        Ventas form = new Ventas(usuario);
                        form.setVisible(true);
                        this.dispose();
                    }else if(privilegios == 3){
                        bodega form = new bodega(usuario);
                        form.setVisible(true);
                        this.dispose();
                    }else if(privilegios == 4){
                        rrhh form = new rrhh(usuario);
                        form.setVisible(true);
                        this.dispose();
                    }
                }
            }else{
                System.out.println("Error: ");
            }
        }catch(Exception e){
            System.out.println("Error: " + e);
        }
    }
    
    public void crear_funcion(){
        String id_sala = salas[text_sala.getSelectedIndex()][0];
        String id_pelicula = movies[text_pelicula.getSelectedIndex()][0];
        String hora_inicio = text_hora.getSelectedItem()+":"+text_minutos.getSelectedItem();
        String hora_final = text_hora_fin.getText();
        String fecha = text_anio.getSelectedItem()+"-"+text_mes.getSelectedItem()+"-"+text_dia.getSelectedItem();
        Statement st;
        if(id_sala == null || id_pelicula == null || hora_inicio == null || hora_final == null || fecha == null){
            JOptionPane.showMessageDialog(null,"CAMPOS INCOMPLETOS");
        }else{
            String stmt = "insert into funcion values(default,'"+id_sala+"','"+id_pelicula+"','"+hora_inicio+"','"+hora_final+"','"+fecha+"')";
            try{
                st = con.createStatement();
                st.executeUpdate(stmt);
                JOptionPane.showMessageDialog(null,"FUNCION AGREGADA CON EXITO");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Error: "+e);
            }
        }
    }
    
    
    public void hora_fin(){
        int hora = Integer.valueOf(text_hora.getItemAt(text_hora.getSelectedIndex()));
        int minuto = Integer.valueOf(text_minutos.getItemAt(text_minutos.getSelectedIndex()));
        int duracion = Integer.valueOf(movies[text_pelicula.getSelectedIndex()][3]);
        int horas = duracion/60;
        int minutos = duracion%60;
        String minuto_text = "";
        String hora_text = "";
        hora = hora + horas;
        minuto = minuto + minutos;        
        while(minuto > 59){
            minuto = minuto - 60;
            hora = hora + 1;
        }
        if(minuto < 10){
            minuto_text = "0" + minuto;
        }else{
            minuto_text = "" +minuto;
        }
        while(hora > 23){
            hora = hora - 24;
        }
        if(hora < 10){
            hora_text = "0" + hora;
        }else{
            hora_text = "" +hora;
        }
        
        
        text_hora_fin.setText(hora_text+":"+minuto_text);
    }
    
    
    public void llenar_sala(){
        String tipo = movies[text_pelicula.getSelectedIndex()][2];
        String stmt = "select s.* from sala s inner join tipo_sala t on s.id_tipo_sala = t.id_tipo_sala WHERE t.tipo LIKE '%"+tipo+"%'";
        int result = 0;
        salas =  new String[100][2];
        text_sala.removeAllItems();
        try{
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(stmt);
            while(rs.next()){
                salas[result][0] = String.valueOf(rs.getInt("id_sala"));
                salas[result][1] = rs.getString("id_tipo_sala");
                text_sala.addItem(" ("+tipo+") SALA: "+salas[result][0]);
                result ++;
            }
           
        }catch(Exception e){
            System.out.println("Error: " + e);
        }
       
    }
    /**
     *  
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(funcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(funcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(funcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(funcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new funcion(usuario).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> text_anio;
    private javax.swing.JComboBox<String> text_dia;
    private javax.swing.JComboBox<String> text_hora;
    private javax.swing.JLabel text_hora_fin;
    private javax.swing.JComboBox<String> text_mes;
    private javax.swing.JComboBox<String> text_minutos;
    private javax.swing.JComboBox<String> text_pelicula;
    private javax.swing.JComboBox<String> text_sala;
    private javax.swing.JLabel text_usuario;
    // End of variables declaration//GEN-END:variables
}
