/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinema_proyect;

import Conex.Conexion;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author monit
 */
public class nueva_sala extends javax.swing.JFrame {
    public static int usuario;
    Conexion cc = new Conexion();
    Connection con = cc.Conexion();
    String cui[] = new String[100];
    String tipo[][] = new String[10][2];
    public nueva_sala(int id_usuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        usuario = id_usuario;
        text_usuario.setText("UsuarioID: "+usuario);
        String stmt = "select cui from empleado where id_estado = 1";
        String stmt1 = "select * from tipo_sala";
        try{
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(stmt);
            int i=0;
            while(rs.next()){
                cui[i] = rs.getString("cui");
                if(cui[i] != null){
                    text_cui.addItem(cui[i]);
                }
                i++;
            }
            st = con.createStatement();
            rs = st.executeQuery(stmt1);
            i=0;
            while(rs.next()){
                tipo[i][0] = rs.getString("id_tipo_sala");
                tipo[i][1] = rs.getString("tipo");
                if(tipo[i][1] != null){
                    text_tipo.addItem(tipo[i][1]);
                }
                i++;
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error: "+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        text_usuario = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        text_tipo = new javax.swing.JComboBox<>();
        text_cui = new javax.swing.JComboBox<>();
        text_columnas = new javax.swing.JSpinner();
        text_filas = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setText("NUEVA SALA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        text_usuario.setText("Usuario: ");
        jPanel1.add(text_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 150, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("COLUMNAS (ASIENTOS)");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 210, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("TIPO DE SALA");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 168, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("ENCARGADO");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 168, 30));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("FILAS (ASIENTOS)");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 168, 30));

        jPanel1.add(text_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 230, 30));

        jPanel1.add(text_cui, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 230, 30));

        text_columnas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(text_columnas, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 100, 30));

        text_filas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(text_filas, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 100, 30));

        jButton1.setBackground(new java.awt.Color(153, 153, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("CREAR SALA");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 380, 50));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/return.png"))); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(833, 10, 50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        crear_sala();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        regresar();
    }//GEN-LAST:event_jButton3MouseClicked
    public void regresar(){
        String us = "select id_privilegios from usuario where id_usuario = '"+usuario+"'";
        int result = 0;
        try{
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(us);
            
            if(rs.next()){
                result = 1;
                if(result == 1){
                    int privilegios = rs.getInt("id_privilegios");
                    if(privilegios == 1){
                        admin form = new admin(usuario);
                        form.setVisible(true);
                        this.dispose();
                    }else if(privilegios == 2){
                        Ventas form = new Ventas(usuario);
                        form.setVisible(true);
                        this.dispose();
                    }else if(privilegios == 3){
                        bodega form = new bodega(usuario);
                        form.setVisible(true);
                        this.dispose();
                    }else if(privilegios == 4){
                        rrhh form = new rrhh(usuario);
                        form.setVisible(true);
                        this.dispose();
                    }
                }
            }else{
                System.out.println("Error: ");
            }
        }catch(Exception e){
            System.out.println("Error: " + e);
        }
    }
    public void crear_sala(){
        String id_cui = cui[text_cui.getSelectedIndex()];
        String id_tipo_sala = tipo[text_tipo.getSelectedIndex()][0];
        
        int filas = (Integer)text_filas.getValue();
        int columnas = (Integer)text_columnas.getValue();
        int cap = filas * columnas;
        String stmt;
        String insert;
        Statement st;
        ResultSet rs;
        boolean exito = false;
        int id_sala = 0;
        insert = "insert into sala values (default,'"+id_tipo_sala+"','"+id_cui+"','"+cap+"','"+filas+"','"+columnas+"')";
        
        try{
            st = con.createStatement();
            st.executeUpdate(insert);
            String id = "select MAX(id_sala) as id from sala";
            rs = st.executeQuery(id);
            if(rs.next()){
                id_sala = rs.getInt("id");
                exito = true;
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error: "+e);
        }
        
        
        
        
        
        
        if(exito){
            for(int i = 0; i<filas; i++){
                for(int j = 0; j<columnas; j++){
                    try{
                        st = con.createStatement();
                        stmt = "insert into asientos (id_sala,no_asiento,disponibilidad_uso) values('"+id_sala+"','"+((char)('A'+i))+(j+1)+"','1')";
                        st.executeUpdate(stmt);
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null,"Error: "+e);
                    }
                }
            }
            JOptionPane.showMessageDialog(null,"SALA AGREAGADA CON EXITO");
        }else{
            JOptionPane.showMessageDialog(null,"Error: Error al agregar sala");
        }
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nueva_sala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nueva_sala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nueva_sala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nueva_sala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nueva_sala(usuario).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner text_columnas;
    private javax.swing.JComboBox<String> text_cui;
    private javax.swing.JSpinner text_filas;
    private javax.swing.JComboBox<String> text_tipo;
    private javax.swing.JLabel text_usuario;
    // End of variables declaration//GEN-END:variables
}
